### ISSUE TITLE
Add wrecker-ui to LTS 9

### ISSUE THREAD

**Issue by bergmark** [fpco/lts-haskell#76] opened 2017-11-20 15:55 UTC
https://github.com/fpco/stackage/pull/2858#issuecomment-345735981

**Comment by DanBurton** [comment] 2017-12-10 20:34
I can't quite figure out how to wrangle the constraints to allow for `wrecker-ui` in LTS 9. The problem is its dependency, `distributed-process-simplelocalnet`.

- the newest version (distributed-process-simplelocalnet-0.2.4) requires a version of `network-transport` that is too new (1 major bump ahead: need 0.5.* but got 0.4.*)
- the next-to-newest version (distributed-process-simplelocalnet-0.2.3.3) requires a version of `distributed-process`, which in turn, requires a version of `syb` which is too old (1 major bump behind, need <0.7 but got 0.7.*)

**Comment by juhp** [comment] 2017-12-16 12:10
Package is not in Nightly either for the record

**Comment by snoyberg** [comment] 2017-12-28 09:40
I just ran into this as well. Closing, it can be reopened if the dependency issue is resolved.

**Closed by snoyberg** 2017-12-28 09:40 UTC
Labels: lts-9
